/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// #include "stm32f0xx.h"
#include "stm32f0xx_gpio.h"
#include "stm32f0xx_i2c.h"
#include <stdio.h>
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



//! I2C2 occupied by accelerometer
I2C_Handle_t I2C1_Handle;


/**
 * @brief Initializes I2C1 GPIO pins. 
 * 
 * @warning Internal pullups used.
 * 
 */
static void I2C1_GPIO_Init()
{
    GPIO_Handle_t I2C1_Pins;

    // Port B
    I2C1_Pins.GPIOx = GPIOB;

    // Alternate function
    I2C1_Pins.GPIO_Config.GPIO_PinMode = ALT;

    // Output type : Open Drain
    I2C1_Pins.GPIO_Config.GPIO_PinOPType = GPIO_OPENDRAIN;

    // Enable pull up resistors (internal)
    I2C1_Pins.GPIO_Config.GPIO_PinPuPd = PULL_UP;

    // Set Alternate function to I2C1
    //? STM32F072RBT6 datasheet Table 16
    I2C1_Pins.GPIO_Config.GPIO_PinAltFunc = 1; // I2C1

    // Pin speed : Fast
    I2C1_Pins.GPIO_Config.GPIO_PinSpeed = FAST;


    // Set SCL
    I2C1_Pins.GPIO_Config.GPIO_PinNo = GPIO_8;
    GPIO_Init(&I2C1_Pins);


    // Set SDA
    I2C1_Pins.GPIO_Config.GPIO_PinNo = GPIO_9;
    GPIO_Init(&I2C1_Pins);
}

static void I2C1_Init()
{
    I2C1_GPIO_Init();

    // Select I2C1
    I2C1_Handle.I2Cx = I2C1;
    
    // I2C clock speed
    I2C1_Handle.I2C_Config.sclSpeed         = I2C_SCL_SPEED_SM;
    
    // I2C bus address
    I2C1_Handle.I2C_Config.deviceAddress    = I2C_DEFAULT_ADDRESS;

    I2C_Init(&I2C1_Handle);
}




int main(void)
{
    I2C1_Init();



    /* Loop forever */
	while(true)
    {

    }
}
